### ISSUE TITLE
What is the purpose of the new HTTPPost operator

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.cppws#16]
What is the purpose of the new HTTPPost operator or 
why can the operator com.ibm.streamsx.inet.http::HTTPRequest not be used in this case?
Are there features missing?

**Comment by nysenthil** [comment]
Hi Joerg,
I explained this to you sometime in May/2020. It was requested by a customer for them to test and accept the use of IBM Streams in a public cloud deployment. Following are some of the key reasons. I can discuss more details with you if you can ping me via slack later this week.

1) They wanted simplicity in this operator to have the exact features they needed without other bells and whistles and for it to be in the same toolkit as the C++ WebSocket operators they needed for their work.
2) They had severe performance issues in sending data from the Cloud Data Center (in city A) to their corporate network (in city B that is 1200 miles away) over a non-dedicated network link via the public Internet. So, we had to iteratively build a slim operator that met their acceptance criteria.
3) They wanted an easy way to send text/binary data and receive text/binary data from/to their applications all using a single operator. It was an important requirement they had. 
4) Customer wanted to send many request headers and receive many response headers from/to their applications as a map. That is the approach they preferred.

**Comment by joergboe** [comment]
Oh Sorry I forgot this.
