### ISSUE TITLE
Missing dependency in v1.0.4 release or just my wrong setup?

### ISSUE THREAD

**Issue by schubon** [IBMStreams/streamsx.cppws#9]
I'm using the release v1.0.4 and first tried to integrate the WebSocketSendReceive operator in a Streams project maintained in Streams Studio (a.k.a. Eclipse). I ran into a compilation error regarding missing asio files.
As I thought I may have made an error using the operator I opened the sample WebSocketSendReceiveTester in Studio, but ran into the same errors:

---- SPL Build for project WebSocketSendReceiveTester started ---- June 10, 2020 at 11:55:31 AM GMT+2
Building toolkit index
Building main composite: com.ibm.streamsx.cppws.sample::WebSocketServerApp using build configuration: BuildConfig1
/home/schulz2/InfoSphere_Streams/4.3.1.0/bin/sc -M com.ibm.streamsx.cppws.sample::WebSocketServerApp --output-directory=output/com.ibm.streamsx.cppws.sample.WebSocketServerApp/BuildConfig1 --data-directory=data -a -t /home/schulz2/opt/toolkits/streamsx.cppws-1.0.4/com.ibm.streamsx.cppws: --no-toolkit-indexing --no-mixed-mode-preprocessing 
Checking the constraints.
com.ibm.streamsx.cppws.sample/WebSocketServerApp.spl:254:3: CDISP0729W WARNING: A feedback loop was detected on the data path: WebSocketDataReceiver->SentDataNormalizer->WebSocketDataReceiver.
Creating the types.
Creating the functions.
Creating the operators.
Creating the standalone application.
Creating the application model.
Building the binaries.
 [CXX-operator] WebSocketDataReceiver
src/operator/WebSocketDataReceiver.cpp:48:39: fatal error: websocketpp/config/asio.hpp: No such file or directory
 #include <websocketpp/config/asio.hpp>
                                       ^
compilation terminated.
make: *** [build/operator/WebSocketDataReceiver.o] Error 1
CDISP0141E ERROR: The compilation of the generated code failed.

---- SPL Build for project WebSocketSendReceiveTester completed in 4.017 seconds ----

---- SPL Build for project WebSocketSendReceiveTester started ---- June 10, 2020 at 11:56:03 AM GMT+2
Building toolkit index
Building main composite: com.ibm.streamsx.cppws.sample::WebSocketSendReceiveTester using build configuration: BuildConfig
/home/schulz2/InfoSphere_Streams/4.3.1.0/bin/sc -M com.ibm.streamsx.cppws.sample::WebSocketSendReceiveTester --output-directory=output/com.ibm.streamsx.cppws.sample.WebSocketSendReceiveTester/BuildConfig --data-directory=data -a -t /home/schulz2/opt/toolkits/streamsx.cppws-1.0.4/com.ibm.streamsx.cppws: --no-toolkit-indexing --no-mixed-mode-preprocessing 
Checking the constraints.
com.ibm.streamsx.cppws.sample/WebSocketSendReceiveTester.spl:197:3: CDISP0729W WARNING: A feedback loop was detected on the data path: DataThrottler->WebSocketDataSenderReceiver->DataThrottler.
Creating the types.
Creating the functions.
Creating the operators.
Creating the standalone application.
Creating the application model.
Building the binaries.
 [CXX-operator] WebSocketDataSenderReceiver
src/operator/WebSocketDataSenderReceiver.cpp:40:46: fatal error: websocketpp/config/asio_client.hpp: No such file or directory
 #include <websocketpp/config/asio_client.hpp>
                                              ^
compilation terminated.
make: *** [build/operator/WebSocketDataSenderReceiver.o] Error 1
CDISP0141E ERROR: The compilation of the generated code failed.

---- SPL Build for project WebSocketSendReceiveTester completed in 3.059 seconds ----

---- SPL Build for project WebSocketSendReceiveTester started ---- June 10, 2020 at 11:56:28 AM GMT+2
Building toolkit index
Building main composite: com.ibm.streamsx.cppws.sample::WebSocketServerApp using build configuration: BuildConfig1
/home/schulz2/InfoSphere_Streams/4.3.1.0/bin/sc -M com.ibm.streamsx.cppws.sample::WebSocketServerApp --output-directory=output/com.ibm.streamsx.cppws.sample.WebSocketServerApp/BuildConfig1 --data-directory=data -a -t /home/schulz2/opt/toolkits/streamsx.cppws-1.0.4/com.ibm.streamsx.cppws: --no-toolkit-indexing --no-mixed-mode-preprocessing 
Checking the constraints.
Creating the types.
com.ibm.streamsx.cppws.sample/WebSocketServerApp.spl:254:3: CDISP0729W WARNING: A feedback loop was detected on the data path: WebSocketDataReceiver->SentDataNormalizer->WebSocketDataReceiver.
Creating the functions.
Creating the operators.
Creating the standalone application.
Creating the application model.
Building the binaries.
 [CXX-operator] WebSocketDataReceiver
src/operator/WebSocketDataReceiver.cpp:48:39: fatal error: websocketpp/config/asio.hpp: No such file or directory
 #include <websocketpp/config/asio.hpp>
                                       ^
compilation terminated.
make: *** [build/operator/WebSocketDataReceiver.o] Error 1
CDISP0141E ERROR: The compilation of the generated code failed.

---- SPL Build for project WebSocketSendReceiveTester completed in 4.031 seconds ----

**Comment by schubon** [comment]
I get this error, too, when using the sample project's Makefile.

**Comment by nysenthil** [comment]
Dear friend Norbert,
Please follow the steps in this URL and see if your problem goes away. Two of our large enterprise customers here in the USA were up and running with this new toolkit version in 30 minutes earlier this week on Monday.

https://ibmstreams.github.io/streamsx.cppws/docs/user/overview/

-- Senthil.

**Comment by schubon** [comment]
Dear Senthil,

apologies I didn't referred to the document before. The steps described in there helped to resolve the issue I had. Thank you very much for your help and patience.

Kind regards
Norbert
